// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI3mMLkEQtLC9sWw6l29ZFy37l_MJ6MvU',
    appId: '1:647692871806:web:6c3006f9e2680ca3ae102f',
    messagingSenderId: '647692871806',
    projectId: 'expense-tracker-927ae',
    authDomain: 'expense-tracker-927ae.firebaseapp.com',
    storageBucket: 'expense-tracker-927ae.firebasestorage.app',
    measurementId: 'G-LV1LVTM4BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIA6LPZGIYSUu_dpX79o7PHF5b-x_4LnQ',
    appId: '1:647692871806:android:03f79a0da43625a8ae102f',
    messagingSenderId: '647692871806',
    projectId: 'expense-tracker-927ae',
    storageBucket: 'expense-tracker-927ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYG2bOt-fBtLavdYPf-5ONCDQ9C9vCFSg',
    appId: '1:647692871806:ios:6251c5e0462308e3ae102f',
    messagingSenderId: '647692871806',
    projectId: 'expense-tracker-927ae',
    storageBucket: 'expense-tracker-927ae.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYG2bOt-fBtLavdYPf-5ONCDQ9C9vCFSg',
    appId: '1:647692871806:ios:6251c5e0462308e3ae102f',
    messagingSenderId: '647692871806',
    projectId: 'expense-tracker-927ae',
    storageBucket: 'expense-tracker-927ae.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI3mMLkEQtLC9sWw6l29ZFy37l_MJ6MvU',
    appId: '1:647692871806:web:1b2615ec787ca501ae102f',
    messagingSenderId: '647692871806',
    projectId: 'expense-tracker-927ae',
    authDomain: 'expense-tracker-927ae.firebaseapp.com',
    storageBucket: 'expense-tracker-927ae.firebasestorage.app',
    measurementId: 'G-G4EMES0Z8W',
  );
}
